name: satprod

dependencies:
  - conda=4.9.2
  - pip=21.0.1
  - python=3.7.2
  - opencv=3.4.2
  - pip:
    - numpy==1.20.1
    - pandas==1.2.2
    - pyyaml==5.4.1
    - pytest==6.2.2
    - jupyter==1.0.0
    - scikit-learn==0.24.1
    - torch==1.7.1
    - torchvision==0.8.2
    - matplotlib==3.3.4
    - statsmodels==0.12.2
    - seaborn==0.11.1
#    - opencv-python==4.5.1.48